### ISSUE TITLE
Support extensive attribute selectors

### ISSUE THREAD

**Issue by mradionov** [crzrcn/protractor-uisref-locator#2]
What do you think about adding an optional second paremeter to *uiSref* locator, which would accept a single character representing a type of attribute selector([docs here](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)) to be used to query an element?
```
element(by.uiSref('home', '^')) // starts with 'home', e.g.: "home.contacts" or "home.user({ id: 2 })"
element(by.uiSref('list', '$')) // ends with 'list', e.g.: "widgets.list" or "products.list"
```
By default, if not set - simple '=', as it is now.

Not sure if it will be really useful, but sometimes I felt a need in those selectors.
I would love to make a PR, if you approve this feature.

**Comment by crzrcn** [comment]
Can you provide a use case where you felt you needed this?

**Comment by mradionov** [comment]
It could be helpful when you want to pick multiple links on a page with different params or do not want even mention params, because they may be pretty long and can be changed in perspective:
```
<span ui-sref="product.show({ id: product.id, category: product.categoryId })"></span>
```
But I thought about it again and now think that it would be a pretty useless feature and syntax for it is not the best, which will make it hard to use and extend. I do not have any really solid use-cases which will give a reason to implement it. One can always use custom selector `$('[ui-sref^="product.show"]')` if there is a need for it.
