### ISSUE TITLE
Find child of element by uisref

### ISSUE THREAD

**Issue by MathRivest** [crzrcn/protractor-uisref-locator#3]
Doing something like this is ignoring my parent locator

```javascript
element(by.id('myParent')).element(by.uiSref('link-1'))
```

**Comment by crzrcn** [comment]
Closed by #1 released by https://github.com/crzrcn/protractor-uisref-locator/commit/7b4e101b6d9c15a067760ff402ce6895f7e4ef25 (v1.2.0).
